name: @ github.com/schollz
description:  My coding projects

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://schollz.github.io
permalink: /:year/:month/:title/
owner:
    name: schollz
    twitter: zack_118
    github: schollz
    disqus_shortname: schollz-github

ga_id: #
ga_username: #

timezone: Africa/Accra
